apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
  labels:
    app.kubernetes.io/name: cinemaabyss
    app.kubernetes.io/instance: cinemaabyss
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cinemaabyss
    meta.helm.sh/release-namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  # Docker config for ghcr.io registry
  # Created with: kubectl create secret docker-registry dockerconfigjson \
  #   -n cinemaabyss \
  #   --docker-server=ghcr.io \
  #   --docker-username=bezlim \
  #   --docker-password=!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  .dockerconfigjson: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!