apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
  labels:
    app.kubernetes.io/name: cinemaabyss
    app.kubernetes.io/instance: cinemaabyss
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cinemaabyss
    meta.helm.sh/release-namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
data:
  # Docker config for ghcr.io registry
  # Created with: kubectl create secret docker-registry dockerconfigjson \
  #   -n cinemaabyss \
  #   --docker-server=ghcr.io \
  #   --docker-username=bezlim \
  #   --docker-password=<PAT>
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsidXNlcm5hbWUiOiAiYmV6bGltIiwgInBhc3N3b3JkIjogImdocF9wdWFTdnpveWMwSFBqZnBxQXNONXFWSHNUVmlkV2YwT2dDb3kiLCAiYXV0aCI6ICJZbVY2YkdsdE9tZG9jRjl3ZFdGVFRucHZlV013U0ZCcVpuQnhRWE5PTlhGV1NITlVWbWxrVjJZd1QyZERiM2s9In19fQ==
